yeet "Lithium alloc.enum_values wider" in OceanMonumentPieces.java why it will cause `/locate Monument` and whatever invoking monument gen to throw a NoSuchMethodError